### ISSUE TITLE
Cells that only contain an IPython command in a line are being emptied

### ISSUE THREAD

**Issue by bglezseoane** [irahorecka/jupyterblack#96]
When a cell inside a given notebook contains an IPython built-in command, like the following one, after apply Jupiter-Black the cell is emptied.

```
%run ./example.py
```

However, if this cell contains an empty line below, the cell content is preserved. E.g.:

```
%run ./example.py

```

To totally clarify the issue, after applying Jupiter-Black, the content of the two above cells would be, respectively:

```

```

```
%run ./example.py

```

Using Jupyter-Black 0.3.2 and Black 21.9b0.

**Comment by irahorecka** [comment]
Great - thanks for the detailed issue. I'll take a look at this soon (pardon, there are other tasks I have to attend at this moment).

**Comment by bglezseoane** [comment]
It's OK. Thank you for your work! Jupyter-Black is a really useful piece of my daily workflow.

**Comment by ktw1016** [comment]
Same bug here, using jupyterblack 0.3.3 and black 22.1.0
Command I'm having issues with is `!{sys.executable}`

@irahorecka any chance you can take a look at this soon? Thanks for your work!

**Comment by irahorecka** [comment]
Hey @bglezseoane and @ktw1016, thank you both for your patience. I looked into this this morning and fixed the issue. Please install the latest version of jupyterblack (0.3.5). 

Please let me know if this version fixed your issue.

**Comment by irahorecka** [comment]
Hello @bglezseoane and @ktw1016. Both issues should be addressed in the latest release (v0.3.6).

**Comment by bglezseoane** [comment]
Hello, @irahorecka,

I just checked it out with some quick tests and agree it's fixed. Thank you very much for your work!

**Comment by ktw1016** [comment]
@irahorecka I can confirm it's fixed. Thank you! 👍
